# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='task.proto',
  package='anote',
  serialized_pb='\n\ntask.proto\x12\x05\x61note\"\x97\x05\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05titie\x18\x02 \x01(\t\x12\x0c\n\x04note\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x11 \x01(\x05\x12\x12\n\nproject_id\x18\x04 \x01(\x05\x12\x11\n\tparent_id\x18\x05 \x01(\x05\x12\x10\n\x08position\x18\x06 \x01(\x05\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\x12\x12\n\nupdated_at\x18\x08 \x01(\x03\x12\x12\n\ndeleted_at\x18\t \x01(\x03\x12\x18\n\x10recurrence_count\x18\n \x01(\x05\x12\x17\n\x0frecurrence_type\x18\x0b \x01(\x05\x12\x1c\n\x14recurrence_parent_id\x18\x0c \x01(\x05\x12\'\n\ttask_type\x18\r \x01(\x0e\x32\x14.anote.Task.TaskType\x12\x10\n\x08\x64ue_time\x18\x0e \x01(\x03\x12<\n\x08\x64ue_type\x18\x0f \x01(\x0e\x32\x13.anote.Task.DueType:\x15VALID_BEFORE_DUE_TIME\x12\x0f\n\x07\x63ontext\x18\x10 \x03(\t\x12%\n\x05state\x18\x12 \x03(\x0e\x32\x16.anote.Task.TaskStatus\"0\n\x08TaskType\x12\x0f\n\x0bSIMPLE_TASK\x10\x00\x12\x13\n\x0fRECURRENCE_TASK\x10\x01\"?\n\x07\x44ueType\x12\x19\n\x15VALID_BEFORE_DUE_TIME\x10\x00\x12\x19\n\x15VALID_ONLY_ON_THE_DAY\x10\x01\"k\n\nTaskStatus\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0e\n\nACTIONABLE\x10\x02\x12\r\n\tDELEGATED\x10\x03\x12\x0c\n\x08\x44\x45\x46\x45RRED\x10\x04\x12\x0c\n\x08INCUBATE\x10\x05\x12\x08\n\x04\x44ONE\x10\x06')



_TASK_TASKTYPE = descriptor.EnumDescriptor(
  name='TaskType',
  full_name='anote.Task.TaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SIMPLE_TASK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RECURRENCE_TASK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=463,
  serialized_end=511,
)

_TASK_DUETYPE = descriptor.EnumDescriptor(
  name='DueType',
  full_name='anote.Task.DueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='VALID_BEFORE_DUE_TIME', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALID_ONLY_ON_THE_DAY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=513,
  serialized_end=576,
)

_TASK_TASKSTATUS = descriptor.EnumDescriptor(
  name='TaskStatus',
  full_name='anote.Task.TaskStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CREATED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WAITING', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIONABLE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELEGATED', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEFERRED', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INCUBATE', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DONE', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=578,
  serialized_end=685,
)


_TASK = descriptor.Descriptor(
  name='Task',
  full_name='anote.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='anote.Task.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='titie', full_name='anote.Task.titie', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='note', full_name='anote.Task.note', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_id', full_name='anote.Task.user_id', index=3,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='project_id', full_name='anote.Task.project_id', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parent_id', full_name='anote.Task.parent_id', index=5,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='anote.Task.position', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='created_at', full_name='anote.Task.created_at', index=7,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='updated_at', full_name='anote.Task.updated_at', index=8,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deleted_at', full_name='anote.Task.deleted_at', index=9,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recurrence_count', full_name='anote.Task.recurrence_count', index=10,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recurrence_type', full_name='anote.Task.recurrence_type', index=11,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recurrence_parent_id', full_name='anote.Task.recurrence_parent_id', index=12,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_type', full_name='anote.Task.task_type', index=13,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='due_time', full_name='anote.Task.due_time', index=14,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='due_type', full_name='anote.Task.due_type', index=15,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='context', full_name='anote.Task.context', index=16,
      number=16, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='anote.Task.state', index=17,
      number=18, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_TASKTYPE,
    _TASK_DUETYPE,
    _TASK_TASKSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=685,
)

_TASK.fields_by_name['task_type'].enum_type = _TASK_TASKTYPE
_TASK.fields_by_name['due_type'].enum_type = _TASK_DUETYPE
_TASK.fields_by_name['state'].enum_type = _TASK_TASKSTATUS
_TASK_TASKTYPE.containing_type = _TASK;
_TASK_DUETYPE.containing_type = _TASK;
_TASK_TASKSTATUS.containing_type = _TASK;
DESCRIPTOR.message_types_by_name['Task'] = _TASK

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK
  
  # @@protoc_insertion_point(class_scope:anote.Task)

# @@protoc_insertion_point(module_scope)
